name: forge2d_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.4.0
  flame: ^1.30.1
  flame_forge2d: ^0.19.0+4
  flame_kenney_xml: ^0.1.1+14
  xml: ^6.5.0
  equatable: ^2.0.7
  supabase_flutter: ^2.10.3
  flame_audio: ^2.11.11
  vibration: ^3.1.4
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/audio/
